Repository jairoMolina9/flame-bot, pull requests merged in 2020-08, with the labels that each got.

#1 Install dotenv and load token from .env file
  .gitignore
  README.md
  index.js
  package-lock.json
  package.json
Labels: documentation

#19 Update README.md
  README.md
Labels: documentation

#22 edwincarbajal/render a gif for each flame response
  .gitignore
  README.md
  giphy.js
  index.js
  package-lock.json
  package.json
Labels: feature request

#21 Connected Discord bot to a firestore db
  .gitignore
  README.md
  index.js
  package-lock.json
  package.json
Labels: enhancement

#30 To organize commands better and for every command to have their own f…
  README.md
  commands/flame-help.js
  commands/flame-random.js
  commands/flame-save.js
  commands/flame.js
  firestore.js
  help.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#31 User stats command 🚀
  commands/flame-random.js
  commands/flame-save.js
  commands/flame-stats.js
  commands/flame.js
  firestore.js
  index.js
  stats.js
Labels: feature request

#33 edwincarbajal/flame giphy command
  commands/flame-giphy.js
  commands/flame-help.js
  commands/flame-random.js
  giphy.js
  index.js
  stats.js
Labels: enhancement
